export type CountryOption = {
  name: string;
  code: string;
  aliases?: string[];
};

export const COUNTRIES: CountryOption[] = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU", aliases: ["Australien"] },
  { name: "Austria", code: "AT", aliases: ["Österreich", "Osterreich"] },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY", aliases: ["Weißrussland", "Weissrussland"] },
  { name: "Belgium", code: "BE", aliases: ["Belgien"] },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA", aliases: ["Bosnien", "Bosnien und Herzegowina"] },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR", aliases: ["Brasilien"] },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG", aliases: ["Bulgarien"] },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cabo Verde", code: "CV", aliases: ["Cape Verde", "Kap Verde"] },
  { name: "Cambodia", code: "KH", aliases: ["Kambodscha"] },
  { name: "Cameroon", code: "CM", aliases: ["Kamerun"] },
  { name: "Canada", code: "CA", aliases: ["Kanada"] },
  { name: "Central African Republic", code: "CF", aliases: ["Zentralafrikanische Republik"] },
  { name: "Chad", code: "TD", aliases: ["Tschad"] },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO", aliases: ["Kolumbien"] },
  { name: "Comoros", code: "KM", aliases: ["Komoren"] },
  { name: "Congo", code: "CG" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR", aliases: ["Kroatien"] },
  { name: "Cuba", code: "CU", aliases: ["Kuba"] },
  { name: "Cyprus", code: "CY", aliases: ["Zypern"] },
  { name: "Czechia", code: "CZ", aliases: ["Czech Republic", "Tschechien"] },
  { name: "Denmark", code: "DK", aliases: ["Dänemark", "Danemark"] },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO", aliases: ["Dominikanische Republik"] },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG", aliases: ["Ägypten", "Agypten"] },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ", aliases: ["Äquatorialguinea", "Aquatorialguinea"] },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE", aliases: ["Estland"] },
  { name: "Eswatini", code: "SZ", aliases: ["Swaziland"] },
  { name: "Ethiopia", code: "ET", aliases: ["Äthiopien", "Athiopien"] },
  { name: "Fiji", code: "FJ", aliases: ["Fidschi"] },
  { name: "Finland", code: "FI", aliases: ["Finnland"] },
  { name: "France", code: "FR", aliases: ["Frankreich"] },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE", aliases: ["Georgien"] },
  { name: "Germany", code: "DE", aliases: ["Deutschland"] },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR", aliases: ["Griechenland"] },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU", aliases: ["Ungarn"] },
  { name: "Iceland", code: "IS", aliases: ["Island"] },
  { name: "India", code: "IN", aliases: ["Indien"] },
  { name: "Indonesia", code: "ID", aliases: ["Indonesien"] },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ", aliases: ["Irak"] },
  { name: "Ireland", code: "IE", aliases: ["Irland"] },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT", aliases: ["Italien"] },
  { name: "Jamaica", code: "JM", aliases: ["Jamaika"] },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO", aliases: ["Jordanien"] },
  { name: "Kazakhstan", code: "KZ", aliases: ["Kasachstan"] },
  { name: "Kenya", code: "KE", aliases: ["Kenia"] },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG", aliases: ["Kirgisistan"] },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV", aliases: ["Lettland"] },
  { name: "Lebanon", code: "LB", aliases: ["Libanon"] },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY", aliases: ["Libyen"] },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT", aliases: ["Litauen"] },
  { name: "Luxembourg", code: "LU", aliases: ["Luxemburg"] },
  { name: "Madagascar", code: "MG", aliases: ["Madagaskar"] },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV", aliases: ["Malediven"] },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH", aliases: ["Marshallinseln"] },
  { name: "Mauritania", code: "MR", aliases: ["Mauretanien"] },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX", aliases: ["Mexiko"] },
  { name: "Micronesia", code: "FM", aliases: ["Mikronesien"] },
  { name: "Moldova", code: "MD", aliases: ["Moldawien"] },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN", aliases: ["Mongolei"] },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA", aliases: ["Marokko"] },
  { name: "Mozambique", code: "MZ", aliases: ["Mosambik"] },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL", aliases: ["Niederlande", "Holland"] },
  { name: "New Zealand", code: "NZ", aliases: ["Neuseeland"] },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "North Korea", code: "KP", aliases: ["Nordkorea"] },
  { name: "North Macedonia", code: "MK", aliases: ["Nordmazedonien"] },
  { name: "Norway", code: "NO", aliases: ["Norwegen"] },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine", code: "PS", aliases: ["Palästina", "Palastina"] },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG", aliases: ["Papua-Neuguinea"] },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH", aliases: ["Philippinen"] },
  { name: "Poland", code: "PL", aliases: ["Polen"] },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA", aliases: ["Katar"] },
  { name: "Romania", code: "RO", aliases: ["Rumänien", "Rumanien"] },
  { name: "Russia", code: "RU", aliases: ["Russland"] },
  { name: "Rwanda", code: "RW", aliases: ["Ruanda"] },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA", aliases: ["Saudi-Arabien"] },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS", aliases: ["Serbien"] },
  { name: "Seychelles", code: "SC", aliases: ["Seychellen"] },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG", aliases: ["Singapur"] },
  { name: "Slovakia", code: "SK", aliases: ["Slowakei"] },
  { name: "Slovenia", code: "SI", aliases: ["Slowenien"] },
  { name: "Solomon Islands", code: "SB", aliases: ["Salomonen"] },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA", aliases: ["Südafrika", "Sudafrika"] },
  { name: "South Korea", code: "KR", aliases: ["Südkorea", "Sudkorea"] },
  { name: "South Sudan", code: "SS", aliases: ["Südsudan", "Sudsudan"] },
  { name: "Spain", code: "ES", aliases: ["Spanien"] },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Sweden", code: "SE", aliases: ["Schweden"] },
  { name: "Switzerland", code: "CH", aliases: ["Schweiz", "Suisse", "Svizzera"] },
  { name: "Syria", code: "SY", aliases: ["Syrien"] },
  { name: "Taiwan", code: "TW" },
  { name: "Tajikistan", code: "TJ", aliases: ["Tadschikistan"] },
  { name: "Tanzania", code: "TZ", aliases: ["Tansania"] },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL", aliases: ["East Timor", "Osttimor"] },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN", aliases: ["Tunesien"] },
  { name: "Turkey", code: "TR", aliases: ["Türkiye", "Turkiye", "Türkei", "Turkei"] },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE", aliases: ["UAE", "Vereinigte Arabische Emirate"] },
  { name: "United Kingdom", code: "GB", aliases: ["UK", "Great Britain", "Großbritannien", "Grossbritannien", "England"] },
  { name: "United States", code: "US", aliases: ["USA", "United States of America", "Vereinigte Staaten"] },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ", aliases: ["Usbekistan"] },
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican City", code: "VA", aliases: ["Vatikan"] },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE", aliases: ["Jemen"] },
  { name: "Zambia", code: "ZM", aliases: ["Sambia"] },
  { name: "Zimbabwe", code: "ZW", aliases: ["Simbabwe"] },
  { name: "Hong Kong", code: "HK" },
  { name: "Macau", code: "MO" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Greenland", code: "GL", aliases: ["Grönland", "Gronland"] },
  { name: "Faroe Islands", code: "FO", aliases: ["Färöer", "Faroer"] },
  { name: "Gibraltar", code: "GI" },
  { name: "Bermuda", code: "BM" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Aruba", code: "AW" },
  { name: "Curaçao", code: "CW", aliases: ["Curacao"] },
  { name: "Guam", code: "GU" },
  { name: "French Polynesia", code: "PF", aliases: ["Französisch-Polynesien"] },
  { name: "New Caledonia", code: "NC", aliases: ["Neukaledonien"] },
  { name: "Kosovo", code: "XK" }
];

export function countryFlag(code: string) {
  if (code === "XK") return "🇽🇰";
  return code
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

export function matchCountries(query: string, limit = 8) {
  const normalized = normalizeCountryText(query);
  if (!normalized) return [];
  return COUNTRIES
    .map((country) => {
      const values = [country.name, country.code, ...(country.aliases ?? [])].map(normalizeCountryText);
      const starts = values.some((value) => value.startsWith(normalized));
      const includes = values.some((value) => value.includes(normalized));
      return { country, rank: starts ? 0 : includes ? 1 : 2 };
    })
    .filter((entry) => entry.rank < 2)
    .sort((a, b) => a.rank - b.rank || a.country.name.localeCompare(b.country.name))
    .slice(0, limit)
    .map((entry) => entry.country);
}

function normalizeCountryText(value: string) {
  return value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}