import React, { createContext, useContext, useState } from "react";

export type Lang = "en" | "de";

const T = {
  en: {
    openSidebar: "Open Sidebar",
    collapseSidebar: "Collapse Sidebar",
    networkScan: "Network Scan",
    adbCommands: "ADB Commands",
    selected: "selected",
    moveToGroup: "Move to Group",
    clearSelection: "Clear Selection",
    noDevicesInGroup: "No devices\nin this group",
    noGroups: "No groups available",
    device: "Device",
    devicesSelected: (n: number) => `${n} device${n !== 1 ? "s" : ""} selected`,
    errorMoving: "Error moving devices",
    moved: (n: number) => `${n} device${n !== 1 ? "s" : ""} moved`,
    scanComplete: (n: number) => `Scan complete — ${n} device${n !== 1 ? "s" : ""} found`,
    scanFailed: "Scan failed",
    noDeviceSelected: "⚠ No device selected",
    cmdSent: (n: number, cmd: string) =>
      `[Simulation] Command sent to ${n} device${n !== 1 ? "s" : ""}: ${cmd}`,
    noSavedCommands: "No saved commands yet",
    addNetworkSegment: "Add Network Segment",
    defaultPortNote: "Default port — usually no change needed",
    networkSegment: "Network Segment",
    networkScanTitle: "Network Scan for ADB Devices",
    adbCommandTitle: "ADB Command",
    selectDeviceForActions: "Select a device to see actions",
    groups: "Groups",
    devices: "Devices",
    activities: "Activities",
    allDevices: "All Devices",
    smallScreen: "Small Screen",
    syncControl: "Sync Control",
    enable: "Enable",
    disable: "Disable",
    scan: "Scan",
    scanning: "Scanning…",
    run: "Run",
    clearLog: "Clear Log",
    saved: "Saved",
    noSelection: "No selection",
    port: "Port",
    deviceRegistrySubtitle: "Capture device data",
    noDevice: "no device",
    clear: "Clear",
    clearConfirmQuestion: "Are you sure you want to delete this device data?",
    clearConfirmAction: "Yes, delete",
    save: "Save",
    deviceSection: "Device",
    deviceNumber: "Device Number",
    deviceModel: "Device Model",
    addDeviceModel: "Add Device Model",
    vpnCountry: "VPN Country",
    countryCode: "Country Code",
    countryMatchHint: "Select a country to save flag and ISO code.",
    accountSection: "Account",
    firstName: "First Name",
    lastName: "Last Name",
    gmailAddress: "Gmail Address",
    gmailPassword: "Gmail Password",
    secondEmail: "Second E-Mail",
    twoFactorNotes: "2FA Notes",
    paymentSection: "Payment",
    cardHolder: "Card Holder",
    cardType: "Card Type",
    cardNumber: "Card Number",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    billingDate: "Billing Date",
    miscSection: "Notes",
    misc: "Notes",
    scheduleResults: "Schedule",
    scheduleResultsSubtitle: "Planner results and device pickup calendar",
    noSavedSchedule: "No saved schedule yet",
    noSavedScheduleHint: "Generate and save a schedule in the Task Planner first. It will appear here as a device calendar.",
    searchDevice: "Search device…",
    schedulePickupHint: "Later, devices will fetch this plan by stable device identity.",
    scheduleEdit: "Edit",
    scheduleEditActive: "Editing active",
    scheduleDeleteBlocks: (n: number) => `Delete blocks (${n})`,
    scheduleDeleteDaySelection: (n: number) => `Delete day for selection (${n})`,
    scheduleDeleteDayAll: "Delete day for all",
    scheduleCreatePlanSelection: "Create plan for selection",
    scheduleClearSelection: "Clear selection",
    scheduleConfirmDeleteBlocks: (n: number) => `Delete ${n} selected task block${n !== 1 ? "s" : ""}?`,
    scheduleConfirmDeleteDaySelection: (date: string, n: number) => `Delete the full day ${date} for ${n} device${n !== 1 ? "s" : ""}?`,
    scheduleConfirmDeleteDayAll: (date: string) => `Delete the full day ${date} for all devices?`,
    schedulePastCreateBlocked: "A new task plan cannot be created for past days.",
    settings: "Settings",
    settingsTitle: "Settings",
    settingsGeneral: "General",
    settingsGeneralSubtitle: "App-wide defaults",
    settingsDateTimeTitle: "Date & time",
    settingsTimezone: "App timezone",
    settingsTimezoneHint: "This timezone defines when a calendar day starts and when a day is considered past.",
    settingsBrowserTimezone: "Browser timezone",
    settingsCurrentDate: "Current app date",
    info: "Info",
    deviceInfoTitle: "Device info",
    deviceInfoHint: "Saved device data",
    edit: "Edit",
    copy: "Copy",
    copied: "Copied",
    actionHome: "Home",
    actionBack: "Back",
    actionVolumeUp: "Volume up",
    actionVolumeDown: "Volume down",
    actionLockScreen: "Lock screen",
    actionRestartDevice: "Restart device",
    technicalSection: "Technical",
    status: "Status",
    model: "Model",
    noSavedDeviceInfo: "No saved device info yet",
    /* ── Task Planner ── */
    dayLetters: ["Su","Mo","Tu","We","Th","Fr","Sa"] as string[],
    dayShort:   ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"] as string[],
    tp_intro: "Create fully automated 24h plans for a single day or the entire week. Select the days, set task durations and generate the schedule.",
    tp_howItWorks: "HOW IT WORKS",
    tp_targetsHeader: "Targets · Fleet avg h/day",
    tp_targetsDesc: "Target: how many hours per day each device runs this activity on average. Drag ↕ on numbers to adjust.",
    tp_lock: "Lock",
    tp_lockDesc: "Locked = task runs in one block (e.g. 5h Artist streaming without interruption). Open = task is split in 2 parts.",
    tp_minMaxDesc: "Daily variance per device. Each device gets a random duration assigned within this range.",
    tp_rangeDesc: "Time window within which the random task duration is placed. The task starts somewhere in this window and runs until its random duration.",
    tp_noRangeNote: "⚠ Without Range: All tasks are scheduled randomly throughout the day per device — no fixed time window.",
    tp_ofDevicesLabel: "of devices %",
    tp_ofDevicesDesc: "How many percent of devices should run this activity within the time window.",
    tp_exampleLabel: "Example Sleep:",
    tp_exampleText: "Min 2h · Max 5h · Range 50% · between 00:00 – 07:00\n→ 50% of devices get a random sleep duration between 2h and 5h. This duration is placed randomly within the window 00:00–07:00, e.g. sleep from 01:30 to 04:30 (3h).",
    tp_varianceHeader: "Variance · Min — Max · Fixed Range",
    tp_total: "Total",
    tp_streaming: "Streaming",
    tp_min: "Min",
    tp_max: "Max",
    tp_btw: "btw",
    tp_range: "Range",
    tp_generateSchedule: "Generate Schedule",
    tp_saveSchedule: "Save Schedule",
    tp_overwriteConfirm: (devices: number, days: number) => `Existing schedule data overlaps with ${devices} device${devices !== 1 ? "s" : ""} on ${days} day${days !== 1 ? "s" : ""}. Overwrite this saved schedule?`,
    tp_replaceSavedScheduleConfirm: "A saved schedule already exists. Saving will replace the current saved schedule. Continue?",
    tp_lockTitleLocked: "Locked: runs as one block. Click to split.",
    tp_lockTitleOpen: "Open: split in 2 parts. Click to lock.",
    tp_enableGlobally: "Enable globally",
    tp_disableGlobally: "Disable globally",
    tp_overview: "Overview",
    tp_hours: "Hours",
    tp_timeline: "Timeline",
    tp_noScheduleYet: "Configure targets on the left, then click \"Generate Schedule\"",
    tp_pastSaveBlocked: "A plan cannot be saved for past days.",
    tp_overwriteTitle: "Overwrite existing plan?",
    tp_overwriteAffected: (devices: number, days: number, dates: string) => `Affected: ${devices} device${devices !== 1 ? "s" : ""} · ${days} day${days !== 1 ? "s" : ""}: ${dates}`,
    tp_overwriteDescription: "Below you can see the already saved plan for this exact scope. Confirming replaces only this scope.",
    tp_overwriteDeviceColumn: "Device",
    tp_overwriteIpColumn: "IP",
    tp_overwriteEmpty: "empty",
    tp_overwriteNoBlocks: "No existing blocks",
    tp_overwriteMoreDevices: (n: number) => `+ ${n} more device${n !== 1 ? "s" : ""} affected`,
    cancel: "Cancel",
    deleteAction: "Delete",
    ok: "OK",
    tp_overwriteConfirmButton: "Overwrite this scope",
  },
  de: {
    openSidebar: "Sidebar öffnen",
    collapseSidebar: "Sidebar einklappen",
    networkScan: "Netzwerk-Scan",
    adbCommands: "ADB-Befehle",
    selected: "ausgewählt",
    moveToGroup: "In Gruppe verschieben",
    clearSelection: "Auswahl aufheben",
    noDevicesInGroup: "Keine Geräte\nin dieser Gruppe",
    noGroups: "Keine Gruppen vorhanden",
    device: "Gerät",
    devicesSelected: (n: number) => `${n} Gerät${n !== 1 ? "e" : ""} ausgewählt`,
    errorMoving: "Fehler beim Verschieben",
    moved: (n: number) => `${n} Gerät${n !== 1 ? "e" : ""} verschoben`,
    scanComplete: (n: number) =>
      `Scan abgeschlossen — ${n} Gerät${n !== 1 ? "e" : ""} gefunden`,
    scanFailed: "Scan fehlgeschlagen",
    noDeviceSelected: "⚠ Kein Gerät ausgewählt",
    cmdSent: (n: number, cmd: string) =>
      `[Simulation] Befehl an ${n} Gerät${n !== 1 ? "e" : ""} gesendet: ${cmd}`,
    noSavedCommands: "Noch keine Befehle gespeichert",
    addNetworkSegment: "Netzwerksegment hinzufügen",
    defaultPortNote: "Standard-Port (muss normalerweise nicht geändert werden)",
    networkSegment: "Netzwerksegment",
    networkScanTitle: "Netzwerk-Scan für ADB-Geräte",
    adbCommandTitle: "ADB-Befehl",
    selectDeviceForActions: "Gerät auswählen um Aktionen zu sehen",
    groups: "Gruppen",
    devices: "Geräte",
    activities: "Aktivitäten",
    allDevices: "Alle Geräte",
    smallScreen: "Small Screen",
    syncControl: "Sync Control",
    enable: "Enable",
    disable: "Disable",
    scan: "Scan",
    scanning: "Scanning…",
    run: "Ausführen",
    clearLog: "Log leeren",
    saved: "Gespeichert",
    noSelection: "Keine Auswahl",
    port: "Port",
    deviceRegistrySubtitle: "Gerätedaten erfassen",
    noDevice: "kein Gerät",
    clear: "Leeren",
    clearConfirmQuestion: "Are you sure you want to delete this device data?",
    clearConfirmAction: "Yes, delete",
    save: "Speichern",
    deviceSection: "Gerät",
    deviceNumber: "Gerätenummer",
    deviceModel: "Gerätemodell",
    addDeviceModel: "Gerätemodell hinzufügen",
    vpnCountry: "VPN-Land",
    countryCode: "Länderkürzel",
    countryMatchHint: "Land auswählen, um Flagge und ISO-Kürzel zu speichern.",
    accountSection: "Account",
    firstName: "Vorname",
    lastName: "Nachname",
    gmailAddress: "Gmail-Adresse",
    gmailPassword: "Gmail-Passwort",
    secondEmail: "Zweite E-Mail",
    twoFactorNotes: "2FA-Notizen",
    paymentSection: "Zahlung",
    cardHolder: "Karteninhaber",
    cardType: "Kartentyp",
    cardNumber: "Kartennummer",
    expiryDate: "Ablaufdatum",
    cvv: "CVV",
    billingDate: "Abrechnungsdatum",
    miscSection: "Notizen",
    misc: "Notizen",
    scheduleResults: "Kalender",
    scheduleResultsSubtitle: "Task-Planner-Ergebnisse und Geräte-Abholplan",
    noSavedSchedule: "Noch kein Zeitplan gespeichert",
    noSavedScheduleHint: "Erzeuge und speichere zuerst einen Zeitplan im Task Planner. Danach erscheint er hier als Geräte-Kalender.",
    searchDevice: "Gerät suchen…",
    schedulePickupHint: "Später holen Geräte diesen Plan über ihre feste Geräte-Identität ab.",
    scheduleEdit: "Bearbeiten",
    scheduleEditActive: "Bearbeiten aktiv",
    scheduleDeleteBlocks: (n: number) => `Blöcke löschen (${n})`,
    scheduleDeleteDaySelection: (n: number) => `Tag für Auswahl löschen (${n})`,
    scheduleDeleteDayAll: "Tag für alle löschen",
    scheduleCreatePlanSelection: "Plan für Auswahl erstellen",
    scheduleClearSelection: "Auswahl leeren",
    scheduleConfirmDeleteBlocks: (n: number) => `${n} ausgewählte Task-Blöcke löschen?`,
    scheduleConfirmDeleteDaySelection: (date: string, n: number) => `Den kompletten Tag ${date} für ${n} Gerät${n !== 1 ? "e" : ""} löschen?`,
    scheduleConfirmDeleteDayAll: (date: string) => `Den kompletten Tag ${date} für alle Geräte löschen?`,
    schedulePastCreateBlocked: "Für vergangene Tage kann kein neuer Taskplan erstellt werden.",
    settings: "Einstellungen",
    settingsTitle: "Einstellungen",
    settingsGeneral: "Allgemein",
    settingsGeneralSubtitle: "App-weite Standards",
    settingsDateTimeTitle: "Datum & Zeit",
    settingsTimezone: "App-Zeitzone",
    settingsTimezoneHint: "Diese Zeitzone bestimmt, wann ein Kalendertag beginnt und ab wann ein Tag als vergangen gilt.",
    settingsBrowserTimezone: "Browser-Zeitzone",
    settingsCurrentDate: "Aktuelles App-Datum",
    info: "Info",
    deviceInfoTitle: "Geräteinfo",
    deviceInfoHint: "Gespeicherte Gerätedaten",
    edit: "Bearbeiten",
    copy: "Kopieren",
    copied: "Kopiert",
    actionHome: "Home",
    actionBack: "Zurück",
    actionVolumeUp: "Lauter",
    actionVolumeDown: "Leiser",
    actionLockScreen: "Bildschirm sperren",
    actionRestartDevice: "Gerät neu starten",
    technicalSection: "Technisch",
    status: "Status",
    model: "Modell",
    noSavedDeviceInfo: "Noch keine Gerätedaten gespeichert",
    /* ── Task Planner ── */
    dayLetters: ["So","Mo","Di","Mi","Do","Fr","Sa"] as string[],
    dayShort:   ["Mo","Di","Mi","Do","Fr","Sa","So"] as string[],
    tp_intro: "Erstelle vollautomatische 24h-Pläne für einen einzelnen Tag oder die ganze Woche. Wähle die Wochentage, bestimme die Taskdauer und generiere den Zeitplan.",
    tp_howItWorks: "WIE ES FUNKTIONIERT",
    tp_targetsHeader: "Ziele · Flotten-Ø h/Tag",
    tp_targetsDesc: "Zielvorgabe: wie viele Stunden pro Tag jedes Gerät diese Aktivität im Durchschnitt ausführt. Drag ↕ auf den Zahlen zum Anpassen.",
    tp_lock: "Schloss",
    tp_lockDesc: "Gesperrt = Task wird am Stück ausgeführt (z.B. 5h Artist-Streaming ohne Unterbrechung). Offen = Task wird in 2 Teile aufgeteilt.",
    tp_minMaxDesc: "Tagesabweichung pro Gerät. Jedes Gerät bekommt eine zufällige Dauer in diesem Bereich zugeteilt.",
    tp_rangeDesc: "Zeitfenster, innerhalb dem die zufällige Dauer des Tasks platziert wird. Der Task startet irgendwo in diesem Fenster und läuft bis zu seiner zufälligen Dauer.",
    tp_noRangeNote: "⚠ Ohne Range: Die Reihenfolge aller Tasks wird pro Gerät zufällig über den gesamten Tag verteilt — kein festes Zeitfenster.",
    tp_ofDevicesLabel: "der Geräte %",
    tp_ofDevicesDesc: "Wie viele Prozent der Geräte diese Aktivität in dem Zeitfenster ausführen sollen.",
    tp_exampleLabel: "Beispiel Sleep:",
    tp_exampleText: "Min 2h · Max 5h · Range 50% · zwischen 00:00 – 07:00\n→ 50% der Geräte erhalten eine zufällige Schlafdauer zwischen 2h und 5h. Diese Schlafdauer wird zufällig irgendwo im Zeitfenster 00:00–07:00 platziert, z.B. Schlaf von 01:30 bis 04:30 (3h).",
    tp_varianceHeader: "Varianz · Min — Max · Festes Fenster",
    tp_total: "Gesamt",
    tp_streaming: "Streaming",
    tp_min: "Min",
    tp_max: "Max",
    tp_btw: "zw.",
    tp_range: "Range",
    tp_generateSchedule: "Zeitplan generieren",
    tp_saveSchedule: "Zeitplan speichern",
    tp_overwriteConfirm: (devices: number, days: number) => `Für ${devices} Gerät${devices !== 1 ? "e" : ""} gibt es an ${days} Tag${days !== 1 ? "en" : ""} bereits gespeicherte Plan-Daten. Gespeicherten Zeitplan überschreiben?`,
    tp_replaceSavedScheduleConfirm: "Es gibt bereits einen gespeicherten Zeitplan. Speichern ersetzt diesen aktuellen Zeitplan. Fortfahren?",
    tp_lockTitleLocked: "Gesperrt: am Stück ausführen. Klick zum Aufteilen.",
    tp_lockTitleOpen: "Offen: wird in 2 Teile aufgeteilt. Klick zum Sperren.",
    tp_enableGlobally: "Global aktivieren",
    tp_disableGlobally: "Global deaktivieren",
    tp_overview: "Überblick",
    tp_hours: "Stunden",
    tp_timeline: "Zeitlinie",
    tp_noScheduleYet: 'Ziele links konfigurieren, dann auf \u201eZeitplan generieren\u201c klicken.',
    tp_pastSaveBlocked: "Für vergangene Tage kann kein Plan gespeichert werden.",
    tp_overwriteTitle: "Bestehenden Plan überschreiben?",
    tp_overwriteAffected: (devices: number, days: number, dates: string) => `Betroffen: ${devices} Gerät${devices !== 1 ? "e" : ""} · ${days} Tag${days !== 1 ? "e" : ""}: ${dates}`,
    tp_overwriteDescription: "Unten siehst du den bereits gespeicherten Plan für genau diesen Bereich. Beim Bestätigen wird nur dieser Bereich ersetzt.",
    tp_overwriteDeviceColumn: "Gerät",
    tp_overwriteIpColumn: "IP",
    tp_overwriteEmpty: "leer",
    tp_overwriteNoBlocks: "Keine bestehenden Blöcke",
    tp_overwriteMoreDevices: (n: number) => `+ ${n} weitere Gerät${n !== 1 ? "e" : ""} betroffen`,
    cancel: "Abbrechen",
    deleteAction: "Löschen",
    ok: "OK",
    tp_overwriteConfirmButton: "Diesen Bereich überschreiben",
  },
};

export type Translations = typeof T["en"];

const LangContext = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}>({ lang: "en", setLang: () => {}, t: T.en });

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  return (
    <LangContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
